### ISSUE TITLE
Flag for 5xx reporting

### ISSUE THREAD

**Issue by netfeed** [WICG/network-error-logging#58] opened 2015-11-10 12:59 UTC
Would it be possible from the server-side to govern how 5xx reports would happen? It's up to the user agent right now to chose if it should include 5xx-errors or not.

So it could be something like, for example:

```
NEL: report-uri="https://example.com/report"; max-age=2592000; includeServerErrors
```

or:

```
NEL: report-uri="https://example.com/report"; max-age=2592000; ignoreServerErrors
```

Where the _includeServerErrors_ would force the client to send 5xx-errors, _ignoreServerErrors_ would skip them and it would be up to the client to decide on its own if the flags was missing.

This would make the error-reporting for these errors more consistent instead of some clients reporting the errors and some skipping them.

**Comment by dcreager** [comment] 2018-06-27 13:30
This is a duplicate of #72.  4xx and 5xx errors will definitely be reported now that successful requests are reported (#63), it's just a question of whether they're reported as `ok` (because the user agent got a response) or `http.error`.

**Closed by dcreager** 2018-06-27 13:30 UTC
